version: "3"

services:

#
#  nginx:
#    restart: always
#    image: nginx:latest
#    expose:
#      - 8080
#    ports:
#      - 80:8080
#    volumes:
#      - ./
#    depends_on:
#      - web




  web:
    container_name: django_template
    restart: always

    build:
      context: ./project/
      dockerfile: Dockerfile

    depends_on:
      - postgres

    ports:
      - 8000:8000

    command: bash -c "sleep 5 && gunicorn -c gunicorn.conf.py project.wsgi"


  postgres:
    image: postgres:12.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata
    env_file: ./project/.env








